### ISSUE TITLE
Executing genrule @com_google_zetasql//zetasql/resolved_ast:run_gen_resolved_ast_cc failed: (Exit 1)

### ISSUE THREAD

**Issue by AseiSugiyama** [diyor28/tf-aarch64#8]
## Environment and target

- Python: 3.10
- TFX: 1.9.0

## Error message

At the `#15 [tfx-build 10/15] RUN chmod +x replace_commits.sh && ./replace_commits.s...` step, the build tool raised this error.

```
#15 1311. ERROR: /root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/external/com_google_zetasql/zetasql/resolved_ast/BUILD:50:23: Executing genrule @com_google_zetasql//zetasql/resolved_ast:run_gen_resolved_ast_cc failed: (Exit 1): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)
#15 1311. 
#15 1311. Use --sandbox_debug to see verbose messages from the sandbox
#15 1311. Traceback (most recent call last):
#15 1311.   File "/root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/sandbox/processwrapper-sandbox/1131/execroot/tfx_bsl/bazel-out/host/bin/external/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.runfiles/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.py", line 33, in <module>
#15 1311.     import jinja2
#15 1311.   File "/root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/sandbox/processwrapper-sandbox/1131/execroot/tfx_bsl/bazel-out/host/bin/external/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.runfiles/jinja/jinja2/__init__.py", line 33, in <module>
#15 1311.     from jinja2.environment import Environment, Template
#15 1311.   File "/root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/sandbox/processwrapper-sandbox/1131/execroot/tfx_bsl/bazel-out/host/bin/external/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.runfiles/jinja/jinja2/environment.py", line 15, in <module>
#15 1311.     from jinja2 import nodes
#15 1311.   File "/root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/sandbox/processwrapper-sandbox/1131/execroot/tfx_bsl/bazel-out/host/bin/external/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.runfiles/jinja/jinja2/nodes.py", line 19, in <module>
#15 1311.     from jinja2.utils import Markup
#15 1311.   File "/root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/sandbox/processwrapper-sandbox/1131/execroot/tfx_bsl/bazel-out/host/bin/external/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.runfiles/jinja/jinja2/utils.py", line 647, in <module>
#15 1311.     from markupsafe import Markup, escape, soft_unicode
#15 1311.   File "/root/.cache/bazel/_bazel_root/69d415f69592c20e8fa96228da1bfb1a/sandbox/processwrapper-sandbox/1131/execroot/tfx_bsl/bazel-out/host/bin/external/com_google_zetasql/zetasql/resolved_ast/gen_resolved_ast.runfiles/markupsafe/__init__.py", line 13, in <module>
#15 1311.     from collections import Mapping
#15 1311. ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)
#15 1311. ----------------
#15 1311. Note: The failure of target @com_google_zetasql//zetasql/resolved_ast:gen_resolved_ast (with exit code 1) may have been caused by the fact that it is running under Python 3 instead of Python 2. Examine the error to determine if that appears to be the problem. Since this target is built in the host configuration, the only way to change its version is to set --host_force_python=PY2, which affects the entire build.
#15 1311. 
#15 1311. If this error started occurring in Bazel 0.27 and later, it may be because the Python toolchain now enforces that targets analyzed as PY2 and PY3 run under a Python 2 and Python 3 interpreter, respectively. See https://github.com/bazelbuild/bazel/issues/7899 for more information.
#15 1311. ----------------
#15 1313. Target //tfx_bsl:move_generated_files failed to build
#15 1313. Use --verbose_failures to see the command lines of failed build steps.
```

Before that error message, I found this WARNING message

```
#15 51.72 WARNING: Download from https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/582c8d236cb079023657287c318ff26adb239002.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
#15 52.11 Loading: 0 packages loaded
```

## Full log

[tfx190_py310.txt](https://github.com/diyor28/tf-aarch64/files/10192579/tfx190_py310.txt)

**Comment by diyor28** [comment]
This might be caused by similar reasons to https://github.com/diyor28/tf-aarch64/issues/9

**Comment by AseiSugiyama** [comment]
Okay. Let's close this issue, too!
